### ISSUE TITLE
Rhino Automation - Reload test cases button doesn't work (no errors console/networking error)

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#56]
![image](https://user-images.githubusercontent.com/70174048/97119223-7b954980-1717-11eb-8811-9fe0d4b286cd.png)

**Comment by gravity-api** [comment]
According to the image it is working (log status is correct).
Reload Test Cases updates the test case cache on client site when working with multiple tabs.
