### ISSUE TITLE
Bug manager - Data driven iteration need to be marked fail "red" instead of just actual result and green pass in step

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#58]
![image](https://user-images.githubusercontent.com/70174048/97119807-64585b00-171b-11eb-946f-093c1f02244a.png)

**Comment by gravity-api** [comment]
Not a bug. XRay cannot show test iterations. Therefore, the last iteration will be the one shown in the steps breakdown. The run status will be fail
