### ISSUE TITLE
Bug manager - doesn't update bug when bug status update manually as resolved and TC failed 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#59]
![image](https://user-images.githubusercontent.com/70174048/97119948-5a832780-171c-11eb-85b8-ec8baa5537f0.png)

**Comment by gravity-api** [comment]
As design. The bug status only change when test pass. If the test will pass all bugs statuses will be updated. We do not want to interfere with internal manual process of bug lifecycle
