### ISSUE TITLE
[Bug manager].[Jira cloud] bug's comments for "update" bug function, show " is To Do" status for execution 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#66]
![image](https://user-images.githubusercontent.com/70174048/97786436-3ad47f00-1bb4-11eb-94c9-99ac9d7f2b5c.png)

**Comment by gravity-api** [comment]
As design.
Default status on bugs is To Do.

Rhino updates the bug and adds in the comments the bug last status.
