### ISSUE TITLE
[Jira Cloud] Xray "old" issue view isn't supported to execute Rhino automation  

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#67]
![image](https://user-images.githubusercontent.com/70174048/97790103-7714d900-1bce-11eb-94bb-15984df3b492.png)
![image](https://user-images.githubusercontent.com/70174048/97790125-9875c500-1bce-11eb-863e-e6af3f94ebc9.png)
![image](https://user-images.githubusercontent.com/70174048/97790140-c3601900-1bce-11eb-9916-22ef9d59d839.png)

**Comment by gravity-api** [comment]
Not a bug.
Rhino does not have nor will have backward compatibility for 3rd party products.
We support only the latest.

Alternatively, you can create your own fork and add support.
