### ISSUE TITLE
New version - Rhino automation ALM console error 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-atlassian#88]
GET http://localhost:8082/rest/raven/1.0/testexec/RHIN-9/configuredTestOrder?_=1610489960347 404
c.supported.XMLHttpRequest.send @ batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=en-US&richediton=true:9607

**Comment by gravity-api** [comment]
This is XRay service, not Rhino.
